#[derive(Copy, Clone, Eq, PartialEq, Debug, Hash)]
pub enum Kind {
    Allocator,
    AnonymousContext,
    AnyProtocolConformanceList,
    ArgumentTuple,
    AssociatedType,
    AssociatedTypeRef,
    AssociatedTypeMetadataAccessor,
    DefaultAssociatedTypeMetadataAccessor,
    AssociatedTypeWitnessTableAccessor,
    BaseWitnessTableAccessor,
    AutoClosureType,
    BoundGenericClass,
    BoundGenericEnum,
    BoundGenericStructure,
    BoundGenericProtocol,
    BoundGenericOtherNominalType,
    BoundGenericTypeAlias,
    BoundGenericFunction,
    BuiltinTypeName,
    CFunctionPointer,
    Class,
    ClassMetadataBaseOffset,
    ConcreteProtocolConformance,
    Constructor,
    CoroutineContinuationPrototype,
    Deallocator,
    DeclContext,
    DefaultArgumentInitializer,
    DependentAssociatedConformance,
    DependentAssociatedTypeRef,
    DependentGenericConformanceRequirement,
    DependentGenericParamCount,
    DependentGenericParamType,
    DependentGenericSameTypeRequirement,
    DependentGenericLayoutRequirement,
    DependentGenericSignature,
    DependentGenericType,
    DependentMemberType,
    DependentPseudogenericSignature,
    DependentProtocolConformanceRoot,
    DependentProtocolConformanceInherited,
    DependentProtocolConformanceAssociated,
    Destructor,
    DidSet,
    Directness,
    DynamicAttribute,
    DirectMethodReferenceAttribute,
    DynamicSelf,
    DynamicallyReplaceableFunctionImpl,
    DynamicallyReplaceableFunctionKey,
    DynamicallyReplaceableFunctionVar,
    Enum,
    EnumCase,
    ErrorType,
    EscapingAutoClosureType,
    NoEscapeFunctionType,
    ExistentialMetatype,
    ExplicitClosure,
    Extension,
    FieldOffset,
    FullTypeMetadata,
    Function,
    FunctionSignatureSpecialization,
    FunctionSignatureSpecializationParam,
    FunctionSignatureSpecializationReturn,
    FunctionSignatureSpecializationParamKind,
    FunctionSignatureSpecializationParamPayload,
    FunctionType,
    GenericPartialSpecialization,
    GenericPartialSpecializationNotReAbstracted,
    GenericProtocolWitnessTable,
    GenericProtocolWitnessTableInstantiationFunction,
    ResilientProtocolWitnessTable,
    GenericSpecialization,
    GenericSpecializationNotReAbstracted,
    GenericSpecializationParam,
    InlinedGenericFunction,
    GenericTypeMetadataPattern,
    Getter,
    Global,
    GlobalGetter,
    Identifier,
    Index,
    IVarInitializer,
    IVarDestroyer,
    ImplEscaping,
    ImplConvention,
    ImplFunctionAttribute,
    ImplFunctionType,
    ImplImpliedSubstitutions,
    ImplSubstitutions,
    ImplicitClosure,
    ImplParameter,
    ImplResult,
    ImplErrorResult,
    InOut,
    InfixOperator,
    Initializer,
    KeyPathGetterThunkHelper,
    KeyPathSetterThunkHelper,
    KeyPathEqualsThunkHelper,
    KeyPathHashThunkHelper,
    LazyProtocolWitnessTableAccessor,
    LazyProtocolWitnessTableCacheVariable,
    LocalDeclName,
    MaterializeForSet,
    MergedFunction,
    Metatype,
    MetatypeRepresentation,
    Metaclass,
    MethodLookupFunction,
    ObjCMetadataUpdateFunction,
    ObjCResilientClassStub,
    FullObjCResilientClassStub,
    ModifyAccessor,
    Module,
    NativeOwningAddressor,
    NativeOwningMutableAddressor,
    NativePinningAddressor,
    NativePinningMutableAddressor,
    NominalTypeDescriptor,
    NonObjCAttribute,
    Number,
    ObjCAttribute,
    ObjCBlock,
    EscapingObjCBlock,
    OtherNominalType,
    OwningAddressor,
    OwningMutableAddressor,
    PartialApplyForwarder,
    PartialApplyObjCForwarder,
    PostfixOperator,
    PrefixOperator,
    PrivateDeclName,
    PropertyDescriptor,
    PropertyWrapperBackingInitializer,
    Protocol,
    ProtocolSymbolicReference,
    ProtocolConformance,
    ProtocolConformanceRefInTypeModule,
    ProtocolConformanceRefInProtocolModule,
    ProtocolConformanceRefInOtherModule,
    ProtocolDescriptor,
    ProtocolConformanceDescriptor,
    ProtocolList,
    ProtocolListWithClass,
    ProtocolListWithAnyObject,
    ProtocolSelfConformanceDescriptor,
    ProtocolSelfConformanceWitness,
    ProtocolSelfConformanceWitnessTable,
    ProtocolWitness,
    ProtocolWitnessTable,
    ProtocolWitnessTableAccessor,
    ProtocolWitnessTablePattern,
    ReabstractionThunk,
    ReabstractionThunkHelper,
    ReabstractionThunkHelperWithSelf,
    ReadAccessor,
    RelatedEntityDeclName,
    RetroactiveConformance,
    ReturnType,
    Shared,
    Owned,
    SILBoxType,
    SILBoxTypeWithLayout,
    SILBoxLayout,
    SILBoxMutableField,
    SILBoxImmutableField,
    Setter,
    SpecializationPassID,
    IsSerialized,
    Static,
    Structure,
    Subscript,
    Suffix,
    ThinFunctionType,
    Tuple,
    TupleElement,
    TupleElementName,
    Type,
    TypeSymbolicReference,
    TypeAlias,
    TypeList,
    TypeMangling,
    TypeMetadata,
    TypeMetadataAccessFunction,
    TypeMetadataCompletionFunction,
    TypeMetadataInstantiationCache,
    TypeMetadataInstantiationFunction,
    TypeMetadataSingletonInitializationCache,
    TypeMetadataDemanglingCache,
    TypeMetadataLazyCache,
    UncurriedFunctionType,
    UnknownIndex,

    // from swift/AST/ReferenceStorage.def
    Weak,
    Unowned,
    Unmanaged,

    UnsafeAddressor,
    UnsafeMutableAddressor,
    ValueWitness,
    ValueWitnessTable,
    Variable,
    VTableThunk,
    VTableAttribute, // note: old mangling only
    WillSet,
    ReflectionMetadataBuiltinDescriptor,
    ReflectionMetadataFieldDescriptor,
    ReflectionMetadataAssocTypeDescriptor,
    ReflectionMetadataSuperclassDescriptor,
    GenericTypeParamDecl,
    CurryThunk,
    DispatchThunk,
    MethodDescriptor,
    ProtocolRequirementsBaseDescriptor,
    AssociatedConformanceDescriptor,
    DefaultAssociatedConformanceAccessor,
    BaseConformanceDescriptor,
    AssociatedTypeDescriptor,
    ThrowsAnnotation,
    EmptyList,
    FirstElementMarker,
    VariadicMarker,
    OutlinedBridgedMethod,
    OutlinedCopy,
    OutlinedConsume,
    OutlinedRetain,
    OutlinedRelease,
    OutlinedInitializeWithTake,
    OutlinedInitializeWithCopy,
    OutlinedAssignWithTake,
    OutlinedAssignWithCopy,
    OutlinedDestroy,
    OutlinedVariable,
    AssocTypePath,
    LabelList,
    ModuleDescriptor,
    ExtensionDescriptor,
    AnonymousDescriptor,
    AssociatedTypeGenericParamRef,
    SugaredOptional,
    SugaredArray,
    SugaredDictionary,
    SugaredParen,

    // Added in Swift 5.1
    AccessorFunctionReference,
    OpaqueType,
    OpaqueTypeDescriptorSymbolicReference,
    OpaqueTypeDescriptor,
    OpaqueTypeDescriptorAccessor,
    OpaqueTypeDescriptorAccessorImpl,
    OpaqueTypeDescriptorAccessorKey,
    OpaqueTypeDescriptorAccessorVar,
    OpaqueReturnType,
    OpaqueReturnTypeOf,
}


pub fn is_decl_name(kind: Kind) -> bool {
    match kind {
        Kind::Identifier => true,
        Kind::LocalDeclName => true,
        Kind::PrivateDeclName => true,
        Kind::RelatedEntityDeclName => true,
        Kind::PrefixOperator => true,
        Kind::PostfixOperator => true,
        Kind::InfixOperator => true,
        Kind::TypeSymbolicReference => true,
        Kind::ProtocolSymbolicReference => true,
        _ => false,
    }
}

pub fn is_any_generic(kind: Kind) -> bool {
    match kind {
        Kind::Structure => true,
        Kind::Class => true,
        Kind::Enum => true,
        Kind::Protocol => true,
        Kind::ProtocolSymbolicReference => true,
        Kind::OtherNominalType => true,
        Kind::TypeAlias => true,
        Kind::TypeSymbolicReference => true,
        _ => false,
    }
}

pub fn is_entity(kind: Kind) -> bool {
    if let Kind::Type = kind {
        true
    } else {
        false
    }
}

pub fn is_requirement(kind: Kind) -> bool {
    match kind {
        Kind::DependentGenericSameTypeRequirement => true,
        Kind::DependentGenericLayoutRequirement => true,
        Kind::DependentGenericConformanceRequirement => true,
        _ => false,
    }
}

pub fn is_context(kind: Kind) -> bool {
    match kind {
        Kind::Allocator => true,
        Kind::AnonymousContext => true,
        Kind::Class => true,
        Kind::Constructor => true,
        Kind::Deallocator => true,
        Kind::DefaultArgumentInitializer => true,
        Kind::Destructor => true,
        Kind::DidSet => true,
        Kind::Enum => true,
        Kind::ExplicitClosure => true,
        Kind::Extension => true,
        Kind::Function => true,
        Kind::Getter => true,
        Kind::GlobalGetter => true,
        Kind::IVarInitializer => true,
        Kind::IVarDestroyer => true,
        Kind::ImplicitClosure => true,
        Kind::Initializer => true,
        Kind::MaterializeForSet => true,
        Kind::ModifyAccessor => true,
        Kind::Module => true,
        Kind::NativeOwningAddressor => true,
        Kind::NativeOwningMutableAddressor => true,
        Kind::NativePinningAddressor => true,
        Kind::NativePinningMutableAddressor => true,
        Kind::OtherNominalType => true,
        Kind::OwningAddressor => true,
        Kind::OwningMutableAddressor => true,
        Kind::PropertyWrapperBackingInitializer => true,
        Kind::Protocol => true,
        Kind::ProtocolSymbolicReference => true,
        Kind::ReadAccessor => true,
        Kind::Setter => true,
        Kind::Static => true,
        Kind::Structure => true,
        Kind::Subscript => true,
        Kind::TypeSymbolicReference => true,
        Kind::TypeAlias => true,
        Kind::UnsafeAddressor => true,
        Kind::UnsafeMutableAddressor => true,
        Kind::Variable => true,
        Kind::WillSet => true,
        Kind::OpaqueReturnTypeOf => true,
        _ => false,
    }
}

pub fn is_func_attr(kind: Kind) -> bool {
    match kind {
        Kind::FunctionSignatureSpecialization => true,
        Kind::GenericSpecialization => true,
        Kind::InlinedGenericFunction => true,
        Kind::GenericSpecializationNotReAbstracted => true,
        Kind::GenericPartialSpecialization => true,
        Kind::GenericPartialSpecializationNotReAbstracted => true,
        Kind::ObjCAttribute => true,
        Kind::NonObjCAttribute => true,
        Kind::DynamicAttribute => true,
        Kind::DirectMethodReferenceAttribute => true,
        Kind::VTableAttribute => true,
        Kind::PartialApplyForwarder => true,
        Kind::PartialApplyObjCForwarder => true,
        Kind::OutlinedVariable => true,
        Kind::OutlinedBridgedMethod => true,
        Kind::MergedFunction => true,
        Kind::DynamicallyReplaceableFunctionImpl => true,
        Kind::DynamicallyReplaceableFunctionKey => true,
        Kind::DynamicallyReplaceableFunctionVar => true,
        _ => false,
    }
}